spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: satyampawar0070@gmail.com
    password: ptuzsiwijfjqlavd
    properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true
             required: true


#  security:
#    user:
#      name: user
#      password: 123

  application:
    name: MeraTodo
