package com.felix.meratodo.enums;

public enum PermissionType {

    USER_READ, USER_UPDATE, USER_DELETE, USER_UPLOAD_AVATAR,

    TEAM_CREATE, TEAM_READ, TEAM_UPDATE, TEAM_DELETE, TEAM_LIST_MEMBERS, TEAM_LIST_PROJECTS,
    TEAM_INVITE, TEAM_UPDATE_ROLE, TEAM_REMOVE_MEMBER, TEAM_LIST_INVITATIONS,

    PROJECT_CREATE, PROJECT_READ, PROJECT_UPDATE, PROJECT_DELETE, PROJECT_LIST, PROJECT_ASSIGN_TEAM,
    PROJECT_REMOVE_TEAM, PROJECT_ARCHIVE, PROJECT_LIST_TASKS,

    TASK_CREATE, TASK_READ, TASK_UPDATE, TASK_DELETE, TASK_LIST, TASK_ASSIGN, TASK_UNASSIGN,
    TASK_ADD_DEPENDENCY, TASK_REMOVE_DEPENDENCY, TASK_LIST_COMMENTS, TASK_ADD_COMMENT
}
